# Build settings
gems:
  - jemoji
  - jekyll-paginate
  
# Site settings
title: "Richardson Lima "
description: > # this means to ignore newlines until "email:"
   A brain dump about technology and some restrict interests. 

email: rick@richardsonlima.com.br 
#blog logo
logo: "/assets/images/richardson_avatar_social.jpeg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/photo-1618171889969-0feeb769fe78.png"

name: 'Richardson Lima'
author: 'Richardson Lima'
author_image: "/assets/images/richardson_avatar_social.jpeg"

paginate:	100

url: "https://richardsonlima.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@richdevsecops'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

google_analytics: UA-48988720-2

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/richdevsecops
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/richardsonlima
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

