# -----------------------------------------------------------------------------
# Build Settings & Collections
# -----------------------------------------------------------------------------

collections:
  hidden:
    output: true
    permalink: /hidden/:name/
  slides:
    output: true
    permalink: /slides/:name

# Consolidated Defaults: Assigning layouts to folders and collections
defaults:
  - scope:
      path: ""
      type: hidden
    values:
      layout: page
      sitemap: false
      robots: noindex
  - scope:
      path: ""
    values:
      layout: post
  - scope:
      path: "_posts"
    values:
      layout: post
  - scope:
      path: "_slides"
    values:
      layout: slides

# -----------------------------------------------------------------------------
# Markdown & Plugins
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
lstrip_whitespace: true

kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

plugins:
  - jekyll-archives-v2
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate
  - jekyll-regex-replace
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-tabs
  - jekyll-terser
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji

# -----------------------------------------------------------------------------
# Site Metadata
# -----------------------------------------------------------------------------

title: "Richardson Lima"
url: "https://richardsonlima.github.io"
baseurl: ""
paginate: 500
google_analytics: G-6SCN0W0C28
enable_math: true
enable_darkmode: true

# Social Mapping
social:
  - icon: twitter
    url: https://twitter.com/richdevsecops
  - icon: github
    url: https://github.com/richardsonlima
  - icon: desktop 
    url: /slides/
    desc: Presentations